#!/bin/bash

puits=false
sourc=false
protocol="tcp"
port=`expr \`id -u\` % 3000 + 14578`

usage() { echo "Usage: $0 [[-p|-s] [-t (tcp|mictcp)]" 1>&2; exit 1; }

while getopts "pst:" o; do
    case "${o}" in
        t)
            protocol=${OPTARG}
            if [ "$protocol" != "tcp" ] && [ "$protocol" != "mictcp" ]; then
                usage
                exit 1
            fi
            ;;
        p)
            puits=true
            ;;
        s)
            sourc=true
            ;;
        *)
            usage
            ;;
    esac
done

if ([ "$puits" = true ] && [ "$sourc" = true ]) || ([ "$puits" = false ] && [ "$sourc" = false ])  ; then
    usage
    exit 1
fi

if [ "$puits" = true ]; then

    echo "Lancement du puits, protocole " $protocol
    /mnt/c/'Program Files (x86)'/VideoLAN/VLC/vlc.exe rtp://127.0.0.1:$port > /dev/null 2>&1 &

    if [ "$protocol" = "mictcp" ]; then
        cd build
        ./gateway -p -t $protocol $port &
    cd ..
    fi
fi

if [ "$sourc" = true ]; then

    echo "Lancement de la source, protocol " $protocol
    cd build
    ./gateway -s -t $protocol 127.0.0.1 $port &
    cd ..
fi

echo "Appuyez sur ENTREE pour arreter"
read line

echo "Arret"
/mnt/c/Windows/System32/taskkill.exe /IM vlc.exe
killall -9 gateway > /dev/null 2>&1

